/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package leitorarquivode;

import javax.swing.JFileChooser;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FilenameFilter;
import java.io.IOException;
import java.util.List;
import java.util.ArrayList;
import java.text.NumberFormat;

/**
 *
 * @author canti
 */
public class framePrincipal extends javax.swing.JFrame {

    List<File> list = new ArrayList();

    /**
     * Creates new form framePrincipal
     */
    public framePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jDialog2 = new javax.swing.JDialog();
        jLPasta = new javax.swing.JLabel();
        jTPastaSelecionada = new javax.swing.JTextField();
        jBSelecionar = new javax.swing.JButton();
        jBProcessar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTResult = new javax.swing.JTextArea();
        jBGerarCapas = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Processador de Arquivo DE");
        setLocationByPlatform(true);

        jLPasta.setText("Pasta");

        jTPastaSelecionada.setEditable(false);
        jTPastaSelecionada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPastaSelecionadaActionPerformed(evt);
            }
        });

        jBSelecionar.setText("Selecionar");
        jBSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSelecionarActionPerformed(evt);
            }
        });

        jBProcessar.setText("Processar");
        jBProcessar.setEnabled(false);
        jBProcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBProcessarActionPerformed(evt);
            }
        });

        jTResult.setEditable(false);
        jTResult.setColumns(20);
        jTResult.setRows(5);
        jScrollPane1.setViewportView(jTResult);

        jBGerarCapas.setText("Gerar Capas");
        jBGerarCapas.setEnabled(false);
        jBGerarCapas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGerarCapasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLPasta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTPastaSelecionada, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBSelecionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBProcessar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBGerarCapas)
                        .addGap(0, 82, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPasta)
                    .addComponent(jTPastaSelecionada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBSelecionar)
                    .addComponent(jBProcessar)
                    .addComponent(jBGerarCapas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTPastaSelecionadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTPastaSelecionadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTPastaSelecionadaActionPerformed

    private void jBSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSelecionarActionPerformed
        jBGerarCapas.setEnabled(false);
        jBProcessar.setEnabled(false);
        //Seleção do arquivo
        JFileChooser filechooser = new JFileChooser();
        filechooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        filechooser.setCurrentDirectory(new java.io.File("."));
        //Abre a caixa pra seleção do arquivo
        int returnVal = filechooser.showOpenDialog(null);
        //Inicializa o filtro pra pegar somente arquivos ".ret"
        FilenameFilter filter = new OnlyExt("ret");
        //Pega o arquivo selecionado
        File selDir = filechooser.getSelectedFile();

        //Testa o que o usuário clicou
        switch (returnVal) {
            case JFileChooser.APPROVE_OPTION: //Ok
                jTPastaSelecionada.setText(selDir.getAbsolutePath());
                //Itera sobre os arquivos no diretório selecionado usando o filtro
                for (File file : selDir.listFiles(filter)) {
                    System.out.println(file);
                    list.add(file);
                }
                jBGerarCapas.setEnabled(true);
                jBProcessar.setEnabled(true);
                break;

            case JFileChooser.CANCEL_OPTION: //Cancelar
                jTPastaSelecionada.setText("Pasta não selecionada");
                break;
            case JFileChooser.ERROR_OPTION: //shit happens...
                break;
        }

    }//GEN-LAST:event_jBSelecionarActionPerformed

    private void jBProcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBProcessarActionPerformed
        double valor_total = 0;
        int qtde_contratos;
        qtde_contratos = 0;
        jTResult.setText(null);
        jTResult.append("Quantide de arquivos encontrados: ");
        jTResult.append(String.valueOf(list.size()) + " \n \n");
        processadorArquivoDE a = new processadorArquivoDE();
        for (File file : list) {
            a.processa(file);
            jTResult.append(file.getName() + "\n");
            jTResult.append("Valor total: ");
            jTResult.append(a.getValorArquivoFormatado() + "\n");
            jTResult.append("Quantidade de Contratos: ");
            jTResult.append(String.valueOf(a.getTotalContratos()) + "\n");
            jTResult.append("---------------------------");
            jTResult.append("\n \n");
            valor_total += a.getValorArquivoAsDouble();
            qtde_contratos += a.getTotalContratos();
        }
        jTResult.append("Valor total dos Arquivos: ");
        jTResult.append(NumberFormat.getCurrencyInstance().format(valor_total));
        jTResult.append("\n Quantidade total de contratos: ");
        jTResult.append(String.valueOf(qtde_contratos));
        
    }//GEN-LAST:event_jBProcessarActionPerformed

    private void jBGerarCapasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGerarCapasActionPerformed
        // TODO add your handling code here:
        for (File file : list ){
            try {
                geradorCapas gc = new geradorCapas(file);
                gc.writeCapa();
                jTResult.append("\n");
                jTResult.append("Gerando arquivo: ");
                jTResult.append(gc.getNomeDoArquivo());
                jTResult.append("\n");
                System.out.println(gc.getNomeDoArquivo());
            } catch (IOException e) {
                e.printStackTrace();
            }
            
        }
    }//GEN-LAST:event_jBGerarCapasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new framePrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBGerarCapas;
    private javax.swing.JButton jBProcessar;
    private javax.swing.JButton jBSelecionar;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLPasta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTPastaSelecionada;
    private javax.swing.JTextArea jTResult;
    // End of variables declaration//GEN-END:variables
}
